[2025-04-10 13:09:45,918: INFO: main: Logging is Implemented]
[2025-04-19 12:20:18,369: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 12:20:18,593: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 12:22:16,207: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 12:22:16,212: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 12:22:16,259: INFO: common: created directory at: artifacts]
[2025-04-19 12:22:16,263: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-19 12:22:36,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 12:22:36,747: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 12:22:36,750: INFO: common: created directory at: artifacts]
[2025-04-19 12:22:36,752: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-19 12:22:39,790: INFO: 2266689133: File is downloaded]
[2025-04-19 12:48:20,745: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-19 12:48:20,745: ERROR: main: DataIngestionTrainingPipeline.initiate_data_ingestion() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "E:\TextSummarizer\main.py", line 9, in <module>
    data_ingestion_pipeline.initiate_data_ingestion()
TypeError: DataIngestionTrainingPipeline.initiate_data_ingestion() missing 1 required positional argument: 'self'
[2025-04-19 13:02:38,354: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-19 13:02:38,354: ERROR: main: name 'self' is not defined]
Traceback (most recent call last):
  File "E:\TextSummarizer\main.py", line 9, in <module>
    data_ingestion_pipeline.initiate_data_ingestion(self)
NameError: name 'self' is not defined
[2025-04-19 13:03:00,138: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-19 13:03:00,139: ERROR: main: DataIngestionTrainingPipeline.initiate_data_ingestion() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "E:\TextSummarizer\main.py", line 9, in <module>
    data_ingestion_pipeline.initiate_data_ingestion()
TypeError: DataIngestionTrainingPipeline.initiate_data_ingestion() missing 1 required positional argument: 'self'
[2025-04-19 13:04:20,834: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-19 13:04:20,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 13:04:20,841: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 13:04:20,843: INFO: common: created directory at: artifacts]
[2025-04-19 13:04:20,843: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-19 13:04:20,843: INFO: data_ingestion: File already exits]
[2025-04-19 13:04:21,331: INFO: main: Stage Data Ingestion Stage Completed]
[2025-04-19 13:26:49,753: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 17:46:02,317: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 17:46:34,011: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 17:46:34,077: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 17:46:34,093: INFO: common: created directory at: artifacts]
[2025-04-21 17:46:34,111: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-21 18:11:14,799: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-21 18:11:15,468: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 18:11:16,068: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-21 18:11:16,081: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 18:11:16,081: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 18:11:16,081: INFO: common: created directory at: artifacts]
[2025-04-21 18:11:16,081: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-21 18:11:16,081: INFO: data_ingestion: File already exits]
[2025-04-21 18:11:16,723: INFO: main: Stage Data Ingestion Stage Completed]
[2025-04-21 18:11:16,723: INFO: main: stage Data Transformation Stage initiated]
[2025-04-21 18:11:16,726: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 18:11:16,726: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 18:11:16,726: INFO: common: created directory at: artifacts]
[2025-04-21 18:11:16,726: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-21 18:11:24,171: INFO: main: Stage Data Transformation Stage Completed]
[2025-04-21 18:52:51,873: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 18:57:45,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 18:57:45,984: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 18:57:46,179: INFO: common: created directory at: artifacts]
[2025-04-21 18:57:46,181: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-21 19:56:04,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 19:56:05,228: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 19:56:05,413: INFO: common: created directory at: artifacts]
[2025-04-21 19:56:05,526: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-21 20:01:09,676: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:01:09,680: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:01:09,682: INFO: common: created directory at: artifacts]
[2025-04-21 20:01:09,683: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-21 20:21:35,848: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-21 20:21:36,496: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 20:21:37,553: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-21 20:21:37,554: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:21:37,556: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:21:37,557: INFO: common: created directory at: artifacts]
[2025-04-21 20:21:37,557: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-21 20:21:37,557: INFO: data_ingestion: File already exits]
[2025-04-21 20:21:38,522: INFO: main: Stage Data Ingestion Stage Completed]
[2025-04-21 20:21:38,523: INFO: main: stage Data Transformation Stage initiated]
[2025-04-21 20:21:38,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:21:38,526: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:21:38,526: INFO: common: created directory at: artifacts]
[2025-04-21 20:21:38,526: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-21 20:21:42,150: INFO: main: Stage Data Transformation Stage Completed]
[2025-04-21 20:21:42,151: INFO: main: stage Model Trainer Stage initiated]
[2025-04-21 20:21:42,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:21:42,155: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:21:42,156: INFO: common: created directory at: artifacts]
[2025-04-21 20:21:42,156: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-21 20:22:06,184: ERROR: main: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`]
Traceback (most recent call last):
  File "E:\TextSummarizer\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "E:\TextSummarizer\src\TextSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 13, in initiate_model_trainer
    model_trainer.train()
  File "E:\TextSummarizer\src\TextSummarizer\components\model_trainer.py", line 22, in train
    trainer_args = TrainingArguments(
                   ^^^^^^^^^^^^^^^^^^
  File "<string>", line 135, in __init__
  File "C:\Users\DELL\anaconda3\Lib\site-packages\transformers\training_args.py", line 1808, in __post_init__
    self.device
  File "C:\Users\DELL\anaconda3\Lib\site-packages\transformers\training_args.py", line 2344, in device
    return self._setup_devices
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\anaconda3\Lib\site-packages\transformers\utils\generic.py", line 62, in __get__
    cached = self.fget(obj)
             ^^^^^^^^^^^^^^
  File "C:\Users\DELL\anaconda3\Lib\site-packages\transformers\training_args.py", line 2214, in _setup_devices
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`
[2025-04-21 20:24:08,841: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-21 20:24:09,376: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 20:24:10,476: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-21 20:24:10,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:24:10,478: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:24:10,478: INFO: common: created directory at: artifacts]
[2025-04-21 20:24:10,507: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-21 20:24:10,507: INFO: data_ingestion: File already exits]
[2025-04-21 20:24:11,493: INFO: main: Stage Data Ingestion Stage Completed]
[2025-04-21 20:24:11,493: INFO: main: stage Data Transformation Stage initiated]
[2025-04-21 20:24:11,502: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:24:11,502: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:24:11,502: INFO: common: created directory at: artifacts]
[2025-04-21 20:24:11,502: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-21 20:24:14,385: INFO: main: Stage Data Transformation Stage Completed]
[2025-04-21 20:24:14,385: INFO: main: stage Model Trainer Stage initiated]
[2025-04-21 20:24:14,388: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:24:14,390: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:24:14,391: INFO: common: created directory at: artifacts]
[2025-04-21 20:24:14,391: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-21 20:49:28,150: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-21 20:49:29,053: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 20:49:30,312: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-21 20:49:30,312: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:49:30,312: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:49:30,312: INFO: common: created directory at: artifacts]
[2025-04-21 20:49:30,312: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-21 20:49:30,312: INFO: data_ingestion: File already exits]
[2025-04-21 20:49:31,293: INFO: main: Stage Data Ingestion Stage Completed]
[2025-04-21 20:49:31,293: INFO: main: stage Data Transformation Stage initiated]
[2025-04-21 20:49:31,299: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:49:31,304: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:49:31,305: INFO: common: created directory at: artifacts]
[2025-04-21 20:49:31,306: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-21 20:49:38,404: INFO: main: Stage Data Transformation Stage Completed]
[2025-04-21 20:49:38,404: INFO: main: stage Model Trainer Stage initiated]
[2025-04-21 20:49:38,406: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 20:49:38,407: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 20:49:38,409: INFO: common: created directory at: artifacts]
[2025-04-21 20:49:38,409: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-21 22:34:50,135: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 22:39:38,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 22:39:38,374: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 22:39:38,411: INFO: common: created directory at: artifacts]
[2025-04-21 22:39:38,653: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-21 22:43:49,985: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 22:43:52,602: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-21 22:43:52,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 22:43:52,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 22:43:52,610: INFO: common: created directory at: artifacts]
[2025-04-21 22:43:52,610: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-21 22:43:52,611: INFO: data_ingestion: File already exits]
[2025-04-21 22:43:53,222: INFO: main: Stage Data Ingestion Stage Completed]
[2025-04-21 22:43:53,223: INFO: main: stage Data Transformation Stage initiated]
[2025-04-21 22:43:53,227: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 22:43:53,230: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 22:43:53,230: INFO: common: created directory at: artifacts]
[2025-04-21 22:43:53,231: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-21 22:44:00,130: INFO: main: Stage Data Transformation Stage Completed]
[2025-04-21 22:44:00,131: INFO: main: stage Model Trainer Stage initiated]
[2025-04-21 22:44:00,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 22:44:00,141: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 22:44:00,142: INFO: common: created directory at: artifacts]
[2025-04-21 22:44:00,143: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-21 22:44:35,664: ERROR: main: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy']
Traceback (most recent call last):
  File "E:\TextSummarizer\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "E:\TextSummarizer\src\TextSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 13, in initiate_model_trainer
    model_trainer.train()
  File "E:\TextSummarizer\src\TextSummarizer\components\model_trainer.py", line 22, in train
    trainer_args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'
[2025-04-21 22:47:55,840: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-21 22:48:10,053: INFO: main: stage Data Ingestion Stage initiated]
[2025-04-21 22:48:10,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 22:48:10,164: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 22:48:10,170: INFO: common: created directory at: artifacts]
[2025-04-21 22:48:10,172: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-21 22:48:10,173: INFO: data_ingestion: File already exits]
[2025-04-21 22:48:10,663: INFO: main: Stage Data Ingestion Stage Completed]
[2025-04-21 22:48:10,664: INFO: main: stage Data Transformation Stage initiated]
[2025-04-21 22:48:10,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 22:48:10,679: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 22:48:10,680: INFO: common: created directory at: artifacts]
[2025-04-21 22:48:10,681: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-21 22:48:14,093: INFO: main: Stage Data Transformation Stage Completed]
[2025-04-21 22:48:14,093: INFO: main: stage Model Trainer Stage initiated]
[2025-04-21 22:48:14,097: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-21 22:48:14,100: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-21 22:48:14,100: INFO: common: created directory at: artifacts]
[2025-04-21 22:48:14,101: INFO: common: created directory at: artifacts/model_trainer]
